### ISSUE TITLE
customEntityTransform not applied in list items because of wrong Param in getListMarkup

### ISSUE THREAD

**Issue by teknologist** [jpuri/draftjs-to-html#10]
Hi,

there is a bug in the code in index.js:

`
 const listHtml = getListMarkup(
          listBlocks,
          entityMap,
          hashtagConfig,
          customEntityTransform
        );
`

Should inlcude the directional paramater:

`
 const listHtml = getListMarkup(
          listBlocks,
          entityMap,
          hashtagConfig,
directional,
          customEntityTransform
        );
`

The missing paramater blocks entity rendering in list items.

**Comment by teknologist** [comment]
I don't think you need a pull request for such a small change.

Commit is here in my fork:

https://github.com/teknologist/draftjs-to-html/commit/1824c62bf42ffdfd5fdbb75e8299685dfb93ac23

**Comment by jpuri** [comment]
Hey @teknologist: can you plz create PR for this.

**Comment by jpuri** [comment]
Closed by this pr: https://github.com/jpuri/draftjs-to-html/pull/11

Upgrade will be released soon.
