### ISSUE TITLE
Cannot import draftToHTML

### ISSUE THREAD

**Issue by bvn13** [jpuri/draftjs-to-html#13]
`import draftToHtml from 'draftjs-to-html';`

imports nothing, cannot be called.

**Comment by jpuri** [comment]
I do not see a reason for this issue, can you plz make sure you have npm dependency installed `draftjs-to-html`.

**Comment by jpuri** [comment]
Plz feel free to re-open if you still face this issue.

**Comment by zhayes** [comment]
@jpuri  I am meeting the same problem. You should reopen the issue
