### ISSUE TITLE
Thoughts on Deprecating this in favor of draft-convert

### ISSUE THREAD

**Issue by Alex-ray** [jpuri/draftjs-to-html#15]
Hey @jpuri , thanks so much for all your hard work on this project!

It was my first go to when searching to a draft-js to html conversion library, while developing I can across a few limitations around your implementation. specifically around entity conversions.

I did fix this by using the [draft-convert](https://github.com/HubSpot/draft-convert) library which is much more robust. 

Curious to hear your thoughts on deprecating this in favor of draft convert to keep everyone on the same page and others don't run into similar pitfalls?

**Comment by jpuri** [comment]
Hi @Alex-ray ,

This lib has been made specifically for use with https://github.com/jpuri/react-draft-wysiwyg and takes case of all styling options in it. In addition it will keep evolving with needs of https://github.com/jpuri/react-draft-wysiwyg.

**Comment by Alex-ray** [comment]
Ah got it, that makes a bit more sense; thanks so much for the clarification here @jpuri !

I wonder if referencing that in the docs might be useful?
