### ISSUE TITLE
Code blocks are stripped

### ISSUE THREAD

**Issue by chiedo** [jpuri/draftjs-to-html#20]
Sadly, code block html is not showing up when using

draftToHtml(convertToRaw(editorContent.getCurrentContent()))

All I get is a blank where the code blocks were in the editor.

I confirmed that convertToRaw(editorContent.getCurrentContent()) functions as expected which leaves draftToHTML as the culprit

**Comment by jpuri** [comment]
`draftjs-to-html@0.7.5` has the fix.

**Comment by chiedo** [comment]
Thanks!!!
