### ISSUE TITLE
UTF-8 characters get splitted

### ISSUE THREAD

**Issue by paradoxxxzero** [jpuri/draftjs-to-html#24]
![screenshot from 2017-10-06 11-15-20](https://user-images.githubusercontent.com/271144/31271408-b2533b12-aa87-11e7-9220-e1ff45167208.png)

As you can see the inline style which has a length of 1 is applied on the first byte and not the first character.
It happens here: https://github.com/jpuri/draftjs-to-html/blob/master/js/block.js#L361

NB:
```javascript
> '😁a'.length
3

> '😁a'[0]
"�"

> '😁a'[1]
"�"

> '😁a'[2]
"a"

> [...'😁a']
["😁", "a"]
```

**Comment by jpuri** [comment]
Ah I see, great finding. I will try to fix this soon.
Thanks a lot for reporting.

**Comment by bslipek** [comment]
I am looking forward to this also :)

**Comment by daszkowski** [comment]
Can't wait for solution!

**Comment by celber** [comment]
+1

**Comment by TanyaNegrii** [comment]
Can`t wait for the fix)

**Comment by kamilpuchala** [comment]
+1

**Comment by slomagnieszka** [comment]
+1

**Comment by samdarbinyan** [comment]
+1

**Comment by jpuri** [comment]
Hi All, sorry for the delay. I have been more busy with some personal urgencies last month, but slowly resuming thus project now.

**Comment by sontek** [comment]
@jpuri Glad to have you back! :)

**Comment by stormsilver** [comment]
+1
