### ISSUE TITLE
Wrong image alignment

### ISSUE THREAD

**Issue by StanislavMayorov** [jpuri/draftjs-to-html#28]
Hi. Thank you for your projects.
I think image center/left/right align convertation doesn't work properly. A html output looks differently than in editor.

```
<p>Hey this <strong>editor</strong> rocks</p>
<img src="https://www.shareicon.net/data/128x128/2016/07/08/117367_logo_512x512.png" alt="undefined" style="float:none;height: auto;width: auto"/>
<p>bar</p>
```

![image](https://user-images.githubusercontent.com/11670429/33062677-30106d5c-ceb1-11e7-8c15-5d0a46f07208.png)

**Comment by chasedeanda** [comment]
Seeing the same issue here. Any updates on this @jpuri?

**Comment by jpuri** [comment]
I see center align is giving issue. I will try to soon fix this.

**Comment by mparker11** [comment]
Any luck on this?

**Comment by inspiredjw** [comment]
I had the similar problems.
Make sure you don't lose those styling when you convert them, html <-> draftjs.

Use the below ones for converting.
https://github.com/jpuri/draftjs-to-html
https://github.com/jpuri/html-to-draftjs

**Comment by mparker11** [comment]
@inspiredjw Right, we're in the repo for draftjs-to-html. This is what I'm using. 

I did end up figuring it out, so I can do a pull request later. On line 356, an image's alignment is being determined by the float classes that were chosen based on the the L-C-R hover option in the editor. I changed that block to look like this instead:

```
if (entity.type === 'IMAGE') {
    var textAlign = 'none'; 
    if (entity.data.alignment) {
        //entity.data.alignment is for float using the LCR options on the image
        //'none' means the user clicked center
        if (entity.data.alignment === 'none') { 
            textAlign = 'center';
        } else {
            textAlign = entity.data.alignment;
        }
    }
    return '<p style="text-align:' + textAlign + ';"><img src="' + entity.data.src + '" alt="' + entity.data.alt + '" style="height: ' + entity.data.height + ';width: ' + entity.data.width + '"/>';
  }
```

Basically, I wrap my image inside a paragraph tag, then use the alignment input to add text-align to the paragraph's style.

**Comment by Bariyard** [comment]
@mparker11 
Thank you for very helpful suggestion.
I use part of your code in my project, and add it to customEntityTransform to process 'IMAGE' Entity

```javascript
renderHTML(draftToHtml( JSON.parse(this.state.current.content),
  {
    trigger: '#',
    separator: ' ',
  }, 
  true,
  (entity, text) => {
    if (entity.type === 'IMAGE') {
      var textAlign = 'none'; 
      if (entity.data.alignment) {
          //entity.data.alignment is for float using the LCR options on the image
          //'none' means the user clicked center
          if (entity.data.alignment === 'none') { 
              textAlign = 'center';
          } else {
              textAlign = entity.data.alignment;
          }
      }
      return '<p style="text-align:' + textAlign + ';"><img src="' + entity.data.src + '" alt="' + entity.data.alt + '" style="height: ' + entity.data.height + ';width: ' + entity.data.width + '"/></p>';
    }
}))
```

**Comment by realpratiknikam** [comment]
I'm still having this issue in latest version of `draftjs-to-html`. Any update?

**Comment by ghost** [comment]
> @mparker11
> Thank you for very helpful suggestion.
> I use part of your code in my project, and add it to customEntityTransform to process 'IMAGE' Entity
> 
> ```js
> renderHTML(draftToHtml( JSON.parse(this.state.current.content),
>   {
>     trigger: '#',
>     separator: ' ',
>   }, 
>   true,
>   (entity, text) => {
>     if (entity.type === 'IMAGE') {
>       var textAlign = 'none'; 
>       if (entity.data.alignment) {
>           //entity.data.alignment is for float using the LCR options on the image
>           //'none' means the user clicked center
>           if (entity.data.alignment === 'none') { 
>               textAlign = 'center';
>           } else {
>               textAlign = entity.data.alignment;
>           }
>       }
>       return '<p style="text-align:' + textAlign + ';"><img src="' + entity.data.src + '" alt="' + entity.data.alt + '" style="height: ' + entity.data.height + ';width: ' + entity.data.width + '"/></p>';
>     }
> }))
> ```

Refactored:
(just in case if someone need it :) )

```js
draftToHtml(rawDraft, {}, false, ({ type, data }) => {
        //entity.data.alignment is for float using the LCR options on the image 'none' means the user clicked center
        if (type === 'IMAGE') {
            const alignment = data.alignment || 'none';
            const textAlign = alignment === 'none' ? 'center' : alignment;

            return `
                <p style="text-align:${textAlign};">
                    <img src="${data.src}" alt="${data.alt}" style="height: ${data.height};width: ${data.width}"/>
                </p>
            `;
        }
    });
```
