### ISSUE TITLE
Custom markup transformation

### ISSUE THREAD

**Issue by tammomueller** [jpuri/draftjs-to-html#3]
@jpuri PR #2 

We added functionality to transform custom entities to HTML. As you may recall one of the PRs we created for the editor allowed us to embed tweets, instagram posts, etc.

This is the counter part that allows the transformation of these entities into HTML.
This change is backwards compatible and will not break earlier versions of the package.

Also this PR will take care of PR #1 as you can define your own transformation for link entity.

**Comment by jpuri** [comment]
Just released `draftjs-to-html@0.6.0` merging the PR. I have renamed the parameter to `customEntityTransform` as it was too long.

Thanks a lot 👍
