### ISSUE TITLE
Non-pixel font sizes aren't converted correctly

### ISSUE THREAD

**Issue by mjgreen145** [jpuri/draftjs-to-html#36]
Relates to https://github.com/jpuri/html-to-draftjs/issues/46

Per the CSS spec, `font-size` can take absolute and relative values, as well as global values, e.g:
`font-size: medium;`
`font-size: larger;`
`font-size: inherit;`

This library currently assumes all font sizes are in pixels, and therefore just adds 'px' to the end of the stored font-size.

Steps to reproduce:

1. Go to https://jpuri.github.io/react-draft-wysiwyg/#/demo
2. On the first demo (which shows you the outputted html), copy the text which is there, then paste.

Result:

![image](https://user-images.githubusercontent.com/7217076/36021232-1150652e-0d7d-11e8-9c52-a5e998b68e7f.png)

The outputted html has `font-size: medipx`.

I am working on a fix for this and hope to get a PR open shortly.

**Comment by jpuri** [comment]
Thanks for the PR @mjgreen145
