### ISSUE TITLE
Readme Usage is not clear

### ISSUE THREAD

**Issue by heaplabs** [jpuri/draftjs-to-html#4]
The example usage on the Readme file is as follows:

`
import draftToHtml from 'draftjs-to-html';

const rawContentState = convertToRaw(editorState.getCurrentContent());
const markup = draftToHtml(contentState, directional, customEntityTransform);
`

Its not clear what the arguments `contentState`, `directional`, and `customEntityTransform` should be ? And how is the `rawContentState` supposed to be used to get the markup ?

Thank you,
Akhilesh

**Comment by jpuri** [comment]
Thanks for feedback @heaplabs, I will improve it soon. For now you can refer this: https://github.com/jpuri/react-draft-wysiwyg/blob/master/docs/src/components/Demo/index.js#L66

**Comment by jpuri** [comment]
@heaplabs: I have added more details to readme today. Plz share ur feedbacks. PR also welcome 😄

**Comment by lumio** [comment]
Additional to that: What is `convertToRaw`?

**Comment by jpuri** [comment]
I add some more clarity to readme, hope it helps.
