### ISSUE TITLE
startsWith does not supported in IE 11

### ISSUE THREAD

**Issue by avdeev** [jpuri/draftjs-to-html#6]

**Comment by avdeev** [comment]
Solved, using
https://github.com/mathiasbynens/String.prototype.startsWith

**Comment by jpuri** [comment]
Oh I was not aware of it, I will fix it in the lib soon. Thanks a lot for letting me know.

**Comment by jpuri** [comment]
@avdeev: I have fixed the issue and made a new release today.

**Comment by avdeev** [comment]
Thank you
